package com.dpdocter.enums;

public enum AdmitCardPermissionEnum {
	NATURE_OF_OPERATION(" NATURE_OF_OPERATION"), JOINT_INVOLVEMENT("JOINT_INVOLVEMENT"), XRAY("XRAY"), EXAMINATION(
			"EXAMINATION"), DIAGNOSIS("DIAGNOSIS"), TREATMENTPLAN("TREATMENTPLAN"),COMPLAINT("COMPLAINT"),PERSONAL_HISTORY("PERSONAL_HISTORY"),PAST_HISTORY("PAST_HISTORY"),FAMILY_HISTORY("FAMILY_HISTORY"),
	TIME_OF_ADMISSION("TIME_OF_ADMISSION"), TIME_OF_DISCHARGE("TIME_OF_DISCHARGE"),PRE_OPERATION_ORDERS("PRE_OPERATION_ORDERS"),NURSING_CARE("NURSING_CARE"),
	TIME_OF_OPERATION("TIME_OF_OPERATION"),IP("IP"),ADDRESS("ADDRESS"),IPD_NUMBER("INP_NUMBER"),VITAL_SIGNS("VITAL_SIGNS");
	
	private String permission;

	public String getPermission() {
		return permission;
	}

	AdmitCardPermissionEnum(String permission) {
		this.permission = permission;
	}

}
