package com.dpdocter.enums;

public enum AuditActionType {
	CREATE_APPOINTMENT, UPDATE_APPOINTMENT, CANCLE_APPOINTMENT,
	CREATE_PATIENT,UPDATE_PATIENT,DELETE_PATIENT,
	CREATE_VISIT,UPDATE_VISIT,DELETE_VISIT,
	CREATE_PRESCRIPTION,UPDATE_PRESCRIPTION,DELETE_PRESCRIPTION,
	CREATE_CLINICAL_NOTES,UPDATE_CLINICAL_NOTES,DELETE_CLINICAL_NOTES,
	CREATE_INVOICE,UPDATE_INVOICE,DELETE_INVOICE,
	CREATE_DS,UPDATE_DS,DELETE_DS,
	CREATE_RECEIPT,UPDATE_RECEIPT,DELETE_RECEIPT,
	CREATE_FILES,UPDATE_FILES,DELETE_FILES,
	LOGIN,LOGOUT,UPDATE_PASSWORD,
	CREATE_TREATMENT,UPDATE_TREATMENT,DELETE_TREATMENT,
	UPDATE_DOCTOR_PROFILE,UPDATE_CLINIC_PROFILE,
	UPDATE_SUBSCRIPTION_PLAN,BUY_SMS_CREDITS,
	UPDATE_COUNSULTATION_SETTING,ADD_DOCTOR;
	
}
