package com.dpdocter.enums;

public enum ComponentType {

	CLINICAL_NOTES("CLINICAL_NOTES"), REPORTS("REPORTS"), PRESCRIPTIONS("PRESCRIPTIONS"), ALL("ALL"), BILLING(
			"BILLING"), VISITS("VISITS"), PATIENT("PATIENT"), DOCTOR("DOCTOR"), TREATMENT("TREATMENT"), APPOINTMENT(
					"APPOINTMENT"), CALENDAR_REMINDER("CALENDAR_REMINDER"), INVOICE("INVOICE"), RECEIPT(
							"RECEIPT"), EYE_PRESCRIPTION("EYE_PRESCRIPTION"), CONSENT_FORM(
									"CONSENT_FORM"), DISCHARGE_SUMMARY("DISCHARGE_SUMMARY"), USER_REQUEST(
											"USER_REQUEST"), REFRESH("REFRESH"), USER_ORDER("USER_ORDER"), USER_RECORD(
													"USER_RECORD"), DUE_AMOUNT("DUE_AMOUNT"), ADMIT_CARD(
															"ADMIT_CARD"), LAB_REQUEST("LAB_REQUEST"), REFRESH_REQUEST(
																	"REFRESH_REQUEST"), REFRESH_RESPONSE(
																			"REFRESH_RESPONSE"), OT_REPORTS(
																					"OT_REPORTS"), DELIVERY_REPORTS(
																							"DELIVERY_REPORTS"), DOCTOR_LAB_REPORTS(
																									"DOCTOR_LAB_REPORTS"), CERTIFICATE(
																											"CERTIFICATE");

	private String type;

	private ComponentType(String type) {
		this.type = type;
	}

	public String getType() {
		return type;
	}

}
