package com.dpdocter.enums;

public enum ComponentType {

	CLINICAL_NOTES("CLINICAL_NOTES"), REPORTS("REPORTS"), PRESCRIPTIONS("PRESCRIPTIONS"), ALL("ALL"),
	BILLING("BILLING"), VISITS("VISITS"), PATIENT("PATIENT"), DOCTOR("DOCTOR"), TREATMENT("TREATMENT"),
	APPOINTMENT("APPOINTMENT"), CALENDAR_REMINDER("CALENDAR_REMINDER"), INVOICE("INVOICE"), RECEIPT("RECEIPT"),
	EYE_PRESCRIPTION("EYE_PRESCRIPTION"), CONSENT_FORM("CONSENT_FORM"), DISCHARGE_SUMMARY("DISCHARGE_SUMMARY"),
	USER_REQUEST("USER_REQUEST"), REFRESH("REFRESH"), USER_ORDER("USER_ORDER"), USER_RECORD("USER_RECORD"),
	DUE_AMOUNT("DUE_AMOUNT"), ADMIT_CARD("ADMIT_CARD"), LAB_REQUEST("LAB_REQUEST"), REFRESH_REQUEST("REFRESH_REQUEST"),
	REFRESH_RESPONSE("REFRESH_RESPONSE"), OT_REPORTS("OT_REPORTS"), DELIVERY_REPORTS("DELIVERY_REPORTS"),
	DOCTOR_LAB_REPORTS("DOCTOR_LAB_REPORTS"), CERTIFICATE("CERTIFICATE"), DOCTOR_REFERNCE("DOCTOR_REFERNCE"),
	DENTAL_WORKS("DENTAL_WORKS"), DENTAL_LAB_REQUEST("DENTAL_LAB_REQUEST"),
	LAB_REQUISATION_FORM("LAB_REQUISATION_FORM"), DENTAL_LAB_INSPECTION_REPORT("DENTAL_LAB_INSPECTION_REPORT"),
	REFRESH_DOCTOR_LAB_REPORTS("REFRESH_DOCTOR_LAB_REPORTS"), MULTIPLE_RECEIPT("MULTIPLE_RECEIPT"),
	DENTAL_WORKS_CANCELLATION("DENTAL_WORKS_CANCELLATION"), DENTAL_WORK_REFRESH("DENTAL_WORK_REFRESH"),
	MULTIPLE_CLINICAL_NOTES("MULTIPLE_CLINICAL_NOTES"), PATIENT_CARD("PATIENT_CARD"),
	CALENDER_APPOINTMENT("CALENDER_APPOINTMENT"), FLOW_SHEET("FLOW_SHEET"), PATIENT_REFRESH("PATIENT_REFRESH"),
	APPOINTMENT_STATUS_CHANGE("APPOINTMENT_STATUS_CHANGE"), MULTIPLE_INSPECTION_REPORT("MULTIPLE_INSPECTION_REPORT"),
	APPOINTMENT_REFRESH("APPOINTMENT_REFRESH"), DENTAL_IMAGING_REQUEST("DENTAL_IMAGING_REQUEST"),
	REFRESH_DENTAL_IMAGING("REFRESH_DENTAL_IMAGING"), DENTAL_WORK_INVOICE("DENTAL_WORK_INVOICE"), EVENT("EVENT"),
	DENTAL_WORK_RECEIPT("DENTAL_WORK_RECEIPT"), DENTAL_IMAGE_INVOICE("DENTAL_IMAGE_INVOICE"),
	PRESCRIPTION_REFRESH("PRESCRIPTION_REFRESH"), PATIENT_VISIT_REFRESH("PATIENT_VISIT_REFRESH"),
	CLINICAL_NOTES_REFRESH("CLINICAL_NOTES_REFRESH"), DISCHARGE_SUMMARY_REFRESH("DISCHARGE_SUMMARY_REFRESH"),
	RECEIPT_REFRESH("RECEIPT_REFRESH"), INVOICE_REFRESH("INVOICE_REFRESH"), RECORDS_REFRESH("RECORDS_REFRESH"),
	TREATMENTS_REFRESH("TREATMENTS_REFRESH"), PROCEDURE_SHEET("PROCEDURE_SHEET"),
	SIGNED_UP("SIGNED_UP"),EMAIL_VERIFICATION("EMAIL_VERIFICATION"),ONLINE_CONSULTATION("ONLINE_CONSULTATION"),
	SUBSCRIPTION_NUTRITION_PLAN("SUBSCRIPTION_NUTRITION_PLAN"), NUTRITION_RECORD("NUTRITION_RECORD"),
	REFRESH_DATA_SETTING("REFRESH_DATA_SETTING"), DIET_PLAN("DIET_PLAN"),REFRESH_VACCINATION("REFRESH_VACCINATION"),
	REFRESH_GROWTH_CHART("REFRESH_GROWTH_CHART"),REFRESH_BABY_ACHIEVEMENTS("REFRESH_BABY_ACHIEVEMENTS"),ORDER_PLACED("ORDER_PLACED"),ORDER_CONFIRMED(
			"ORDER_CONFIRMED"),  ORDER_PICKED_UP(
			"ORDER_PICKED_UP"), ORDER_DISPATCHED(
					"ORDER_DISPATCHED"), ORDER_PACKED("ORDER_PACKED"), ORDER_OUT_FOR_DELIVERY("ORDER_OUT_FOR_DELIVERY"), ORDER_DELIVERED("ORDER_DELIVERED"), FITNESS_ASSESSMENT("FITNESS_ASSESSMENT");

	private String type;

	private ComponentType(String type) {
		this.type = type;
	}

	public String getType() {
		return type;
	}

}
