package com.dpdocter.enums;

public enum DischargeSummaryPermissions {

	LABOUR_NOTES("LABOUR_NOTES"), BABY_NOTES("BABY_NOTES"), BIRTH_WEIGHT("BIRTH_WEIGHT"), OPERATIONAL_NOTES(
			"OPERATIONAL_NOTES"), CONDITIONS_AT_DISCHARGE("CONDITIONS_AT_DISCHARGE"), TREATMENT_GIVEN(
					"TREATMENT_GIVEN"), SUMMARY("SUMMARY"), DATE_OF_OPERATION("DATE_OF_OPERATION"), NAME_OF_OPERATION(
							"NAME_OF_OPERATION"), SURGEON_NAME("SURGEON_NAME"), ANESTHETIST_NAME(
									"ANESTHETIST_NAME"), TREATING_CONSULTANT("TREATING_CONSULTANT"), LMP("LMP"), EDD(
											"EDD"), SURGERY_DATE("SURGERY_DATE"), SURGERY_NOTE(
													"SURGERY_NOTE"), BABY_TREATMENT_ADVICE(
																	"BABY_TREATMENT_ADVICE"), MOTHER_TREATMENT_ADVICE(
																			"MOTHER_TREATMENT_ADVICE"), PEDIATRICIAN_NAME(
																					"PEDIATRICIAN_NAME"), TIME_OF_ENTRY_IN_OT(
																							"TIME_OF_ENTRY_IN_OT"), TIME_OF_EXIT_FROM_OT(
																									"TIME_OF_EXIT_FROM_OT"), BLOOD_LOSS(
																											"BLOOD_LOSS"),DIAGRAM("DIAGRAM"),ASSISTANT_DOCTOR("ASSISTANT_DOCTOR")
	,CONSULTANT_DOCTOR("CONSULTANT_DOCTOR"),ANESTHESIA("ANESTHESIA"), AGE_ON_ADMISSION("AGE_ON_ADMISSION"), AGE_ON_DISCHARGE("AGE_ON_DISCHARGE"),
	WEIGHT_ON_ADMISSION("WEIGHT_ON_ADMISSION"), WEIGHT_ON_DISCHARGE("WEIGHT_ON_DISCHARGE"),
	TIME_OF_ADMISSION("TIME_OF_ADMISSION"), TIME_OF_DISCHARGE("TIME_OF_DISCHARGE"),
	TIME_OF_OPERATION("TIME_OF_OPERATION"), REFERENCE_NAME("REFERENCE_NAME"),
	DISCHARGE_STATUS("DISCHARGE_STATUS"), DISCHARGE_OUTCOME("DISCHARGE_OUTCOME"),
	BED_LOG("BED_LOG"), HOSPITAL_COURSE("HOSPITAL_COURSE");
	
	private String permission;

	public String getPermission() {
		return permission;
	}

	private DischargeSummaryPermissions(String permission) {
		this.permission = permission;
	}

}
