package com.dpdocter.enums;

public enum DynamicUIEnum {
	VITALSIGNS("VITALSIGNS"), PRESENTCOMPLAINT("PRESENTCOMPLAINT"), COMPLAINT("COMPLAINT"), 
	PASTHISTORY("PASTHISTORY"), PRESENTHISTORY("PRESENTHISTORY"), MENSTRUALHISTORY("MENSTRUALHISTORY"), 
	FAMILYHISTORY("FAMILYHISTORY"), GENERALEXAM("GENERALEXAM"), SYSTEMEXAM("SYSTEMEXAM"), 
	OBSERVATION("OBSERVATION"), WORKINGDIAGRAM("WORKINGDIAGRAM"), INVESTIGATIONS("INVESTIGATIONS"),
	DIAGRAM("DIAGRAM"), NOTES("NOTES"), DIAGNOSIS("DIAGNOSIS");

	private String uiPermission;

	private DynamicUIEnum(String uiPermission) {
		this.uiPermission = uiPermission;
	}

	public String getUiPermission() {
		return uiPermission;
	}

}