package com.dpdocter.enums;

public enum NutrientGoal {
	RENAL_STONE,
	RENAL_PROBLEM,
	WEIGHT_LOSS_DIET,
	WEIGHT_GAIN_DIET,
	THYROID,
	PCOD,
	FATTY_LIVER,
	LIPID_PROFILE_CONTROL,
	MIGRAINE,
	DEPRESSION,
	MUSCLE_GAIN,
	HAEMOGLOBIN_ENHANCER,
	DIABETES_CONTROL,
	LIPID_LOWERING_DIET,
	CHOLESTEROL,
	SEDENTARY_PLAN,
	EXAM_DIET;
}
