package com.dpdocter.enums;

public enum RankingCountParatmeter {

	NUMBER_OF_RX, EXPERIENCE, NUMBER_OF_PATIENTS, FEEDBACK, APPOINTMENT, NUMBER_OF_LIKES, RECOMMENDATIONS, NUMBER_OF_REQUESTS, NUMBER_OF_RESPONSES, GENERIC_MEDICINE_AVAILABILITY, 
	POINT_IF_ACTIVE, POINT_FOR_PAYMENT_TYPE, POINT_IF_ONLINE_CONSULTATION;
}
