package com.dpdocter.enums;

public enum RankingCountParatmeter {

	NUMBER_OF_RX, EXPERIENCE, NUMBER_OF_PATIENTS, FEEDBACK, APPOINTMENT, NUMBER_OF_LIKES, RECOMMENDATIONS, NUMBER_OF_REQUESTS, NUMBER_OF_RESPONSES, GENERIC_MEDICINE_AVAILABILITY;
}
