package com.dpdocter.enums;

public enum Resource {
	COMPLAINT("COMPLAINT"), OBSERVATION("OBSERVATION"), INVESTIGATION("INVESTIGATION"), DIAGNOSIS("DIAGNOSIS"), 
	NOTES("NOTES"), DIAGRAM("DIAGRAM"), PATIENT("PATIENT"), DRUG("DRUG"), LABTEST("LABTEST"), COUNTRY("COUNTRY"), 
	STATE("STATE"), CITY("CITY"), LANDMARKLOCALITY("LANDMARKLOCALITY"), DOCTOR("DOCTOR"), LOCATION("LOCATION"),
	DIAGNOSTICTEST("DIAGNOSTICTEST"), REFERENCE("REFERENCE"), DISEASE("DISEASE"), TREATMENTSERVICE("TREATMENTSERVICE"), 
	TREATMENTSERVICECOST("TREATMENTSERVICECOST"), DOCTORDRUG("DOCTORDRUG"), ADVICE("ADVICE"), PRESENT_COMPLAINT("PRESENT_COMPLAINT"), 
	PROVISIONAL_DIAGNOSIS("PROVISIONAL_DIAGNOSIS"), GENERAL_EXAMINATION("GENERAL_EXAMINATION"), SYSTEMIC_EXAMINATION("SYSTEMIC_EXAMINATION"), 
	HISTORY_OF_PRESENT_COMPLAINT("HISTORY_OF_PRESENT_COMPLAINT"), MENSTRUAL_HISTORY("MENSTRUAL_HISTORY"), OBSTETRIC_HISTORY("OBSTETRIC_HISTORY"), 
	INDICATION_OF_USG("INDICATION_OF_USG"), PA("PA"), PV("PV"), PS("PS"), ECG("ECG"), XRAY("XRAY"), ECHO("ECHO"), HOLTER("HOLTER"),
	PHARMACY("PHARMACY");

	private String type;

	private Resource(String type) {
		this.type = type;
	}

	public String getType() {
		return type;
	}

}
