package com.dpdocter.enums;

public enum RoleEnum {
    SUPER_ADMIN("SUPER_ADMIN"), HOSPITAL_ADMIN("HOSPITAL_ADMIN"), LOCATION_ADMIN("LOCATION_ADMIN"), DOCTOR("DOCTOR"), PATIENT("PATIENT"),ADMIN("ADMIN"),
    STAFF("STAFF"), PHARMIST("PHARMIST"), CONSULTANT_DOCTOR("CONSULTANT_DOCTOR") , RECEPTIONIST_NURSE("RECEPTIONIST_NURSE") , ACCOUNTANT("ACCOUNTANT"),
    COLLECTION_BOY("COLLECTION_BOY"),COLLECTION_BOY_REFRESH("COLLECTION_BOY_REFRESH"), WEB_DOCTOR("WEB_DOCTOR") ,  DENTAL_COLLECTION_BOY("DENTAL_COLLECTION_BOY") , NUTRITIONIST("NUTRITIONIST"),
    DENTAL_WORK_REFRESH("DENTAL_WORK_REFRESH"),DENTAL_WORKS_CANCELLATION("DENTAL_WORKS_CANCELLATION"), REFRESH("REFRESH"), SCHOOL("SCHOOL") , SCHOOL_BRANCH("SCHOOL_BRANCH");
	
    private String role;

    private RoleEnum(String role) {
	this.role = role;
    }

    public String getRole() {
	return role;
    }

}
