package com.dpdocter.enums;

public enum SMSFormatType {

    CONFIRMED_APPOINTMENT_TO_PATIENT("CONFIRMED_APPOINTMENT_TO_PATIENT"), TENTATIVE_APPOINTMENT_TO_PATIENT("TENTATIVE_APPOINTMENT_TO_PATIENT"), CANCEL_APPOINTMENT_TO_PATIENT_BY_DOCTOR(
	    "CANCEL_APPOINTMENT_TO_PATIENT_BY_DOCTOR"), CANCEL_APPOINTMENT_TO_PATIENT_BY_PATIENT("CANCEL_APPOINTMENT_TO_PATIENT_BY_PATIENT"), APPOINTMENT_REMINDER_TO_PATIENT(
	    "APPOINTMENT_REMINDER_TO_PATIENT"), APPOINTMENT_FOLLOWUP_TO_PATIENT("APPOINTMENT_FOLLOWUP_TO_PATIENT"), RESCHEDULE_APPOINTMENT_TO_PATIENT(
	    "RESCHEDULE_APPOINTMENT_TO_PATIENT");

    private String type;

    public String getType() {
	return type;
    }

    private SMSFormatType(String type) {
	this.type = type;
    }
}
