package com.dpdocter.enums;

public enum TabPermissionsEnum {

	PRESCRIPTION("PRESCRIPTION"), CLINICAL_NOTES("CLINICAL_NOTES"), HISTORY("HISTORY"), TREATMENT("TREATMENT"),
	REPORTS("REPORTS"), DISCHARGE_SUMMARY("DISCHARGE_SUMMARY"), BILLING("BILLING"), MY_FILES("MY_FILES"),
	PROCEDURE_SHEET("PROCEDURE_SHEET"), DISCOUNT("DISCOUNT"), ADMIT_CARD("ADMIT_CARD"), FLOWSHEET("FLOWSHEET"),
	APPOINTMENT("APPOINTMENT"), VISIT("VISIT"), PROFILE("PROFILE"), REGISTER("REGISTER"),DELIVERY_REPORT("DELIVERY_REPORT"),
	DENTAL_IMAGING_REPORT("DENTAL_IMAGING_REPORT"), LAB_REPORTS("LAB_REPORTS"), VACCINATION("VACCINATION"),CONSENT_FORM("CONSENT_FORM"),
	IPD_NOTE("IPD_NOTE"),PRE_OPERATION_ASSESSMENT("PRE_OPERATION_ASSESSMENT"),INITIAL_ASSESSMENT("INITIAL_ASSESSMENT"),NURSE_ADMISSION("NURSE_ADMISSION");

	private String permissions;

	private TabPermissionsEnum(String permissions) {
		this.permissions = permissions;
	}

	public String getPermissions() {
		return permissions;
	}

}
