package com.dpdocter.enums;

public enum UniqueIdInitial {

	APPOINTMENT("H"), PRESCRIPTION("P"), REPORTS("R"), CLINICALNOTES("C"), VISITS("V"), USER("USR"), HOSPITAL("HOS"),
	LOCATION("LOC"), ISSUETRACK("HCI"), FEEDBACK("F"), TREATMENT("T"), USERREPORTS("UR"), PHARMACY("PHR"),
	PHARMACY_REQUEST("PHRQ"), EVENT("E"), CONSENT_FORM("CF"), DISCHARGE_SUMMARY("DS"), PHARMACY_RESPONSE("PHRS"),
	LAB_PICKUP_REQUEST("LPR"), DENTAL_LAB_PICKUP_REQUEST("DLPR"), LAB_PICKUP_SAMPLE("LPS"), COLLECTION_BOYS("CB"),
	ADMIT_CARD("AC"), ORDER_DIAGNOSTIC_TEST("ODT"), OT_REPORTS("OT"), DELIVERY_REPORTS("DR"), DOCTOR_LAB_REPORTS("DLR"),
	FLOW_SHEET("FLWS"), DENTAL_IMAGING("DI"), DIET_PLAN("DP"), NUTRITION_RECORD("NR"), EXPENSE("EXP"),MEDICINE_ORDER("MO");

	private String initial;

	private UniqueIdInitial(String initial) {
		this.initial = initial;
	}

	public String getInitial() {
		return initial;
	}
}
